import type { Lang } from "./intake-schema";

// Every UI string the patient sees, in both languages. Question copy lives in
// the schema next to each question; this is the chrome around it.

const en = {
  clinic: "Hair & Scalp Clinic",
  welcomeTitle: "Before you meet the doctor, a few quick questions.",
  welcomeBody:
    "16 questions, about two minutes. Most are a single tap — and you can speak your answers if you prefer.",
  begin: "Begin",
  resumeTitle: (n: number) => `You have an intake in progress — ${n} of 16 answered.`,
  resume: "Continue where I left off",
  startFresh: "Start fresh",
  demo: "Demo · made-up patients only · no real personal data",
  back: "Back",
  next: "Next",
  continue: "Continue",
  confirm: "Confirm",
  finish: "Finish",
  save: "Save",
  choose: "Choose an answer",
  left: (n: number) => `${n} left`,
  questionOf: (n: number, t: number) => `Question ${n} of ${t}`,
  cardOf: (kind: string, i: number, of: number) => `${kind} ${i} of ${of}`,
  product: "Product",
  procedure: "Procedure",
  fromYourAnswers: "From your answers",
  orTap: "or just tap your answer below",
  speak: "Speak your answer",
  listening: "Listening… tap to stop",
  transcribing: "Understanding…",
  heard: "Heard",
  redo: "Redo",
  tryAgain: "Didn't catch that — tap and try again.",
  micUnavailable: "Mic isn't available here — tapping works just as well.",
  dictate: "Dictate",
  readAloud: "Read aloud",
  readAgain: "Read this again",
  tap: "Tap",
  voice: "Voice",
  mode: "How to answer",
  sayYes: "Say “yes” to confirm, or say your answer again.",
  sayAgain: "Okay — say your answer again.",
  tryAgainVoice: "Didn't catch that — please say it again.",
  differentWay: "Prefer a different way? Try",
  tapping: "Tapping",
  speaking: "Speaking",
  language: "Language",
  reviewEyebrow: "Your answers",
  reviewTitle: "Everything the doctor will see.",
  reviewBody: "Check it over — tap Edit to change anything.",
  edit: "Edit",
  editQ: (n: number) => `Edit question ${n}`,
  looksRight: "Looks right — finish",
  jsonSummary: "Structured data (JSON) — what the clinic receives",
  copy: "Copy JSON",
  copied: "Copied ✓",
  selected: "Text selected — press copy on your keyboard",
  inferredBadge: "from your answers",
  unanswered: "Not answered yet",
  doneEyebrow: "Intake complete",
  doneTitle: "Bas ho gaya.",
  doneBody: "The doctor has your full picture. Please have a seat.",
  doneSample: (s: string) => `The clinic will arrange your ${s} sample.`,
  doneNoSample: "No sample will be collected unless you say so later.",
  seeFilled: "See what I filled",
  startOver: "Start over",
  yearsOld: "years old",
  ageRange: (a: number, b: number) => `Anywhere from ${a} to ${b}`,
  tooLow: (a: number) => `That seems too low — ${a} or more, please.`,
  tooHigh: (b: number) => `That seems too high — ${b} or less, please.`,
  decades: ["Teens", "20s", "30s", "40s", "50+"],
  less: "less",
  more: "more",
  none: "None of these",
  noneDone: "None",
  waterNudge: "You mentioned a change in location or water — borewell or scale-leaving water counts as hard.",
  describePlaceholder: "What happened — in your own words.",
  skipToAnswers: "Skip to answers",
};

const hi: typeof en = {
  clinic: "हेयर और स्कैल्प क्लिनिक",
  welcomeTitle: "डॉक्टर से मिलने से पहले, कुछ छोटे सवाल।",
  welcomeBody: "16 सवाल, लगभग दो मिनट। ज़्यादातर सिर्फ़ एक टैप — चाहें तो बोलकर भी जवाब दे सकते हैं।",
  begin: "शुरू करें",
  resumeTitle: (n) => `आपका फ़ॉर्म अधूरा है — 16 में से ${n} जवाब दिए हैं।`,
  resume: "जहाँ छोड़ा था वहीं से जारी रखें",
  startFresh: "नए सिरे से शुरू करें",
  demo: "डेमो · काल्पनिक मरीज़ · कोई असली निजी जानकारी नहीं",
  back: "पीछे",
  next: "आगे",
  continue: "आगे बढ़ें",
  confirm: "पुष्टि करें",
  finish: "पूरा करें",
  save: "सेव करें",
  choose: "एक जवाब चुनें",
  left: (n) => `${n} बाक़ी`,
  questionOf: (n, t) => `सवाल ${n}, कुल ${t} में से`,
  cardOf: (kind, i, of) => `${kind} ${i} / ${of}`,
  product: "प्रोडक्ट",
  procedure: "प्रोसीजर",
  fromYourAnswers: "आपके जवाबों से",
  orTap: "या नीचे टैप करके जवाब दें",
  speak: "बोलकर जवाब दें",
  listening: "सुन रहे हैं… रोकने के लिए टैप करें",
  transcribing: "समझ रहे हैं…",
  heard: "सुना",
  redo: "फिर से",
  tryAgain: "सुनाई नहीं दिया — टैप करके फिर बोलें।",
  micUnavailable: "माइक उपलब्ध नहीं है — टैप करके जवाब देना उतना ही आसान है।",
  dictate: "बोलकर लिखें",
  readAloud: "पढ़कर सुनाएँ",
  readAgain: "फिर से सुनाएँ",
  tap: "टैप",
  voice: "आवाज़",
  mode: "जवाब कैसे दें",
  sayYes: "पुष्टि के लिए “हाँ” कहें, या अपना जवाब फिर बोलें।",
  sayAgain: "ठीक है — अपना जवाब फिर बोलें।",
  tryAgainVoice: "सुनाई नहीं दिया — कृपया फिर बोलें।",
  differentWay: "दूसरा तरीका चाहिए? आज़माएँ",
  tapping: "टैप करके",
  speaking: "बोलकर",
  language: "भाषा",
  reviewEyebrow: "आपके जवाब",
  reviewTitle: "डॉक्टर को यह सब दिखेगा।",
  reviewBody: "एक बार देख लें — कुछ बदलना हो तो 'बदलें' दबाएँ।",
  edit: "बदलें",
  editQ: (n) => `सवाल ${n} बदलें`,
  looksRight: "सब सही है — पूरा करें",
  jsonSummary: "स्ट्रक्चर्ड डेटा (JSON) — जो क्लिनिक को मिलेगा",
  copy: "JSON कॉपी करें",
  copied: "कॉपी हो गया ✓",
  selected: "टेक्स्ट चुन लिया गया — कीबोर्ड से कॉपी करें",
  inferredBadge: "आपके जवाबों से",
  unanswered: "अभी जवाब नहीं दिया",
  doneEyebrow: "फ़ॉर्म पूरा हुआ",
  doneTitle: "बस हो गया।",
  doneBody: "डॉक्टर के पास आपकी पूरी जानकारी पहुँच गई है। कृपया बैठिए।",
  doneSample: (s) => `क्लिनिक आपका ${s} सैंपल लेने का इंतज़ाम करेगा।`,
  doneNoSample: "जब तक आप न कहें, कोई सैंपल नहीं लिया जाएगा।",
  seeFilled: "मैंने क्या भरा, देखें",
  startOver: "फिर से शुरू करें",
  yearsOld: "साल की उम्र में",
  ageRange: (a, b) => `${a} से ${b} के बीच`,
  tooLow: (a) => `यह बहुत कम लगता है — ${a} या ज़्यादा लिखें।`,
  tooHigh: (b) => `यह बहुत ज़्यादा लगता है — ${b} या कम लिखें।`,
  decades: ["किशोर", "20s", "30s", "40s", "50+"],
  less: "कम",
  more: "ज़्यादा",
  none: "इनमें से कुछ नहीं",
  noneDone: "कोई नहीं",
  waterNudge: "आपने जगह या पानी बदलने की बात कही — बोरवेल या निशान छोड़ने वाला पानी 'हार्ड' गिना जाता है।",
  describePlaceholder: "क्या हुआ था — अपने शब्दों में।",
  skipToAnswers: "सीधे जवाबों पर जाएँ",
};

export const STR: Record<Lang, typeof en> = { en, hi };
